/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as RelationshipsRouteImport } from './routes/relationships'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as ParallelRouteImport } from './routes/parallel'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as GeographicRouteImport } from './routes/geographic'
import { Route as DistributionRouteImport } from './routes/distribution'
import { Route as CompositionRouteImport } from './routes/composition'
import { Route as ComparisonRouteImport } from './routes/comparison'
import { Route as IndexRouteImport } from './routes/index'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipsRoute = RelationshipsRouteImport.update({
  id: '/relationships',
  path: '/relationships',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ParallelRoute = ParallelRouteImport.update({
  id: '/parallel',
  path: '/parallel',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const GeographicRoute = GeographicRouteImport.update({
  id: '/geographic',
  path: '/geographic',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributionRoute = DistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => rootRouteImport,
} as any)
const CompositionRoute = CompositionRouteImport.update({
  id: '/composition',
  path: '/composition',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonRoute = ComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comparison': typeof ComparisonRoute
  '/composition': typeof CompositionRoute
  '/distribution': typeof DistributionRoute
  '/geographic': typeof GeographicRoute
  '/heatmap': typeof HeatmapRoute
  '/parallel': typeof ParallelRoute
  '/radar': typeof RadarRoute
  '/relationships': typeof RelationshipsRoute
  '/trends': typeof TrendsRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comparison': typeof ComparisonRoute
  '/composition': typeof CompositionRoute
  '/distribution': typeof DistributionRoute
  '/geographic': typeof GeographicRoute
  '/heatmap': typeof HeatmapRoute
  '/parallel': typeof ParallelRoute
  '/radar': typeof RadarRoute
  '/relationships': typeof RelationshipsRoute
  '/trends': typeof TrendsRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comparison': typeof ComparisonRoute
  '/composition': typeof CompositionRoute
  '/distribution': typeof DistributionRoute
  '/geographic': typeof GeographicRoute
  '/heatmap': typeof HeatmapRoute
  '/parallel': typeof ParallelRoute
  '/radar': typeof RadarRoute
  '/relationships': typeof RelationshipsRoute
  '/trends': typeof TrendsRoute
  '/upload': typeof UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comparison'
    | '/composition'
    | '/distribution'
    | '/geographic'
    | '/heatmap'
    | '/parallel'
    | '/radar'
    | '/relationships'
    | '/trends'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comparison'
    | '/composition'
    | '/distribution'
    | '/geographic'
    | '/heatmap'
    | '/parallel'
    | '/radar'
    | '/relationships'
    | '/trends'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/comparison'
    | '/composition'
    | '/distribution'
    | '/geographic'
    | '/heatmap'
    | '/parallel'
    | '/radar'
    | '/relationships'
    | '/trends'
    | '/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComparisonRoute: typeof ComparisonRoute
  CompositionRoute: typeof CompositionRoute
  DistributionRoute: typeof DistributionRoute
  GeographicRoute: typeof GeographicRoute
  HeatmapRoute: typeof HeatmapRoute
  ParallelRoute: typeof ParallelRoute
  RadarRoute: typeof RadarRoute
  RelationshipsRoute: typeof RelationshipsRoute
  TrendsRoute: typeof TrendsRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationships': {
      id: '/relationships'
      path: '/relationships'
      fullPath: '/relationships'
      preLoaderRoute: typeof RelationshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parallel': {
      id: '/parallel'
      path: '/parallel'
      fullPath: '/parallel'
      preLoaderRoute: typeof ParallelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geographic': {
      id: '/geographic'
      path: '/geographic'
      fullPath: '/geographic'
      preLoaderRoute: typeof GeographicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribution': {
      id: '/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof DistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composition': {
      id: '/composition'
      path: '/composition'
      fullPath: '/composition'
      preLoaderRoute: typeof CompositionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison': {
      id: '/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof ComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComparisonRoute: ComparisonRoute,
  CompositionRoute: CompositionRoute,
  DistributionRoute: DistributionRoute,
  GeographicRoute: GeographicRoute,
  HeatmapRoute: HeatmapRoute,
  ParallelRoute: ParallelRoute,
  RadarRoute: RadarRoute,
  RelationshipsRoute: RelationshipsRoute,
  TrendsRoute: TrendsRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
